name: Deploy Container

on:
  workflow_call:
    inputs:   
      kustomize-input-directory:
        required: true
        type: string
      kustomize-output-file:
        required: true
        type: string     
      imageName:
        required: false
        type: string   
    secrets:
      AZURE_CREDENTIALS:
        required: true
      AKS_NAME:
        required: true
      SNYK_TOKEN:
        required: true

env:
  RESOURCE_GROUP_NAME: rg-aks-devsecops

jobs:
  scan-kubernetes-manifest-file:
  
    runs-on: self-hosted
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    # Set the target Azure Kubernetes Service (AKS) cluster. 
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ secrets.AKS_NAME }}
        resource-group: ${{ env.RESOURCE_GROUP_NAME }}

    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1.0
      with:        
        tokenPrefix: __        
        tokenSuffix: __        
        files: ${{ inputs.kustomize-input-directory }
      env:          
        imageName: ${{ inputs.imageName }}
        imageTag: ${{ github.sha }}

    - name: Build Kustomize template
      run: |        
        kubectl apply -k ${{ inputs.kustomize-input-directory }} --dry-run=client -oyaml > ${{ inputs.kustomize-output-file }}  

    # Continue on error, this is for demo purpose
    - name: Check configuration files for security issues with Snyk
      continue-on-error: true
      uses: snyk/actions/iac@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        file: ${{ inputs.kustomize-output-file }}

    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif      
    
    - name: Deploy Core Service in Kubernetes
      run: |
        kubectl apply -f ${{ inputs.kustomize-output-file }}

