name: identity-api

on:
  workflow_dispatch:
  push:
    branches:
    - main

    paths:
    - src/BuildingBlocks/**
    - src/Services/Identity/**
    - .github/workflows/identity-api.yml
  
  pull_request:
    branches:
    - main

    paths:
    - src/BuildingBlocks/**
    - src/Services/Identity/**
    - .github/workflows/identity-api.yml

jobs:
  Call-dev-sec-ci:
    uses: ./.github/workflows/dev-sec-ci.yml
    with:
      imageName: identity-api
      projectPath: src/Services/Identity/Identity.API
      projectName: Identity.API.csproj
    secrets:
      AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      AZ_APPINSIGHTS_CONNECTION_STRING: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}  
      AZ_SUBSCRIPTION_TOKEN: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }}