name: webshoppingagg

on:
  workflow_dispatch:
  push:
    branches:
    - main

    paths:
    - src/ApiGateways/Aggregators/Web.Shopping.HttpAggregator/**
    - .github/workflows/webshoppingagg.yml
  
  pull_request:
    branches:
    - main

    paths:
    - src/ApiGateways/Aggregators/Web.Shopping.HttpAggregator/**
    - .github/workflows/webshoppingagg.yml

env:
  SERVICE: webshoppingagg
  IMAGE: webshoppingagg

jobs:
  Call-dev-sec-ci:
    uses: ./.github/workflows/dev-sec-ci.yml
    with:
      imageName: webshoppingagg
      projectPath: src/ApiGateways/Aggregators/Web.Shopping.HttpAggregator
      projectName: Web.Shopping.HttpAggregator.csproj
    secrets:
      AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      AZ_APPINSIGHTS_CONNECTION_STRING: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}  
      AZ_SUBSCRIPTION_TOKEN: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }}